import json, os
from pathlib import Path
from playwright.sync_api import sync_playwright

out = Path(os.environ['CHECK_RESULTS'])
checks, errors = [], []
def check(name, value):
    assert value, name
    checks.append(name)
with sync_playwright() as pw:
    browser = pw.chromium.launch()
    page = browser.new_page(viewport={'width': 1440, 'height': 1000})
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.goto('http://127.0.0.1:5178/review33.html')
    page.wait_for_function('!!window.review33')
    page.locator('#open').click()
    panel = page.locator('[data-jobo-check]')
    panel.wait_for()
    close = panel.get_by_role('button', name='Close', exact=True)
    check('initial focus on close', close.evaluate('(el)=>el===document.activeElement'))
    before = page.evaluate('window.review33.snapshot()')
    group = panel.locator('[data-jobo-check-group] > summary').first
    group.click()
    check('off-day estimate stays labelled in expanded group', panel.locator('[data-jobo-check-attempt="estimate"] [data-jobo-check-estimated]').is_visible())
    panel.locator('[data-jobo-check-notes] > summary').first.click()
    note = panel.get_by_role('button', name='Open Project note in Obsidian')
    note.click()
    check('existing note navigator used', page.evaluate('window.review33Notes[0]') == 'Project note')
    check('reading does not write records', page.evaluate('window.review33.snapshot()') == before)
    check('no edit controls', panel.locator('input, textarea, select, form, [contenteditable=true]').count() == 0)
    note.focus()
    page.evaluate('window.review33.setRows([])')
    panel.get_by_text('No Do recorded for this day.', exact=True).wait_for()
    page.wait_for_function('document.activeElement?.getAttribute("aria-label") === "Close"')
    check('deletion retains focus in Check', close.evaluate('(el)=>el===document.activeElement'))
    shortcuts = page.evaluate('window.review33ShortcutCount')
    page.keyboard.press('ArrowRight')
    page.keyboard.press('Control+z')
    check('underlying view shortcuts blocked', page.evaluate('window.review33ShortcutCount') == shortcuts)
    page.keyboard.press('Tab')
    check('empty panel Tab stays contained', close.evaluate('(el)=>el===document.activeElement'))
    page.keyboard.press('Shift+Tab')
    check('empty panel reverse Tab stays contained', close.evaluate('(el)=>el===document.activeElement'))
    page.evaluate('window.review33.setRows([window.review33.make({timing:"untimed",startTime:null,endDate:null,endTime:null,source:"completion",progress:"completed"})])')
    panel.locator('[data-jobo-check-record]').wait_for()
    check('untimed-only group has no fake zero duration figures', panel.locator('[data-jobo-check-metrics]').count() == 0)
    check('untimed-only row has no measured duration', panel.locator('[data-jobo-check-measured]').count() == 0)
    page.evaluate('window.review33.setLoaded(false);window.review33.setError("storageRead")')
    panel.get_by_role('alert').wait_for()
    check('read failure not empty evidence', panel.get_by_text('No Do recorded for this day.', exact=True).count() == 0)
    check('read failure not visible records', panel.locator('[data-jobo-check-record]').count() == 0)
    page.evaluate('window.review33.reset()')
    panel.locator('[data-jobo-check-record]').wait_for()
    page.keyboard.press('Escape')
    panel.wait_for(state='detached')
    check('focus restored to opener', page.locator('#open').evaluate('(el)=>el===document.activeElement'))
    page.locator('#open').click()
    panel.wait_for()
    for locale in ['en', 'zh-CN', 'de']:
        page.evaluate('(lng)=>window.review33.language(lng)', locale)
        for dark in [False, True]:
            page.evaluate('(dark)=>window.review33.theme(dark)', dark)
            for width in [390, 780, 1440]:
                page.set_viewport_size({'width': width, 'height': 1000})
                page.wait_for_timeout(60)
                check(f'{locale} {dark} {width}: no horizontal overflow', panel.evaluate('(el)=>el.scrollWidth <= el.clientWidth + 1'))
                check(f'{locale} {dark} {width}: no untranslated Check keys', 'jobo.check.' not in panel.inner_text())
        page.screenshot(path=str(out / f'review33-{locale}.png'))
    check('no browser errors', not errors)
    browser.close()
(out / 'review-browser.json').write_text(json.dumps({'passed': len(checks), 'checks': checks, 'page_errors': errors}, ensure_ascii=False, indent=2))
print(f'{len(checks)} Check review browser assertions passed')
