import {describe,it,expect,vi,afterEach} from 'vitest';
import {IDBFactory} from 'fake-indexeddb';
import {createJoboStore} from '../jobo/store.js';
import {createJobuData,mergeJobuRecords,pickJobuRevision,materializeJobu,validateJobuRecords,stable} from './data.js';
import {createDurablePlannerStore} from './plannerStore.js';
import {createWish,defaultDocument,updateWish} from '../lifeplanner/model.js';
import {STORAGE_KEY} from '../lifeplanner/store.js';
import {mergeSyncData} from '../mergeSync.js';
import {shredState,applyRemoteEntity,applyRemoteDelete,isInsertOnly} from '../sync/dbAdapter.js';
const row=(id='a',extra={})=>({version:1,id,entityId:'note:x',kind:'doNote',value:{text:id},deleted:false,updatedAt:'2026-09-27T00:00:00.000Z',...extra});
const disposers=[];afterEach(()=>{disposers.splice(0).forEach(f=>f());vi.useRealTimers();});
function memory(seed=[]){let value=structuredClone(seed),tail=Promise.resolve();const store={fail:false,readFail:false,readonly:false,read:async()=>store.readFail?{ok:false}:{ok:true,value:structuredClone(value)},writable:async()=>!store.readonly,update:fn=>{const job=tail.then(()=>{if(store.fail)return {ok:false,error:'quota'};try{value=structuredClone(fn(value));return {ok:true,value:structuredClone(value)};}catch(e){return {ok:false,error:e.message};}});tail=job.then(()=>{});return job;}};return store;}
function controller(store,extra={}){let n=0;const data=createJobuData({store,uuid:()=>`revision-${++n}`,now:()=> '2026-09-27T00:00:00.000Z',...extra});disposers.push(()=>data.dispose());return data;}
describe('Jobu immutable revisions',()=>{
 it.each([[row('a'),row('b')],[row('a'),row('b',{updatedAt:'2026-09-27T08:00:00+08:00'})]])('picks deterministically even with equal instants written in different offsets',(a,b)=>{expect(pickJobuRevision(a,b)).toEqual(pickJobuRevision(b,a));});
 it('union is associative, commutative, idempotent; concurrent text is retained',()=>{const a=[row('a')],b=[row('b')],c=[row('c',{deleted:true})];expect(mergeJobuRecords(a,b)).toEqual(mergeJobuRecords(b,a));expect(mergeJobuRecords(mergeJobuRecords(a,b),c)).toEqual(mergeJobuRecords(a,mergeJobuRecords(b,c)));expect(mergeJobuRecords(a,a)).toEqual(a);expect(mergeJobuRecords(a,b)).toHaveLength(2);expect(materializeJobu([...a,...b,...c]).get('note:x').deleted).toBe(true);expect(mergeJobuRecords(undefined,undefined)).toBeUndefined();});
 it.each([{version:2},{value:{a:undefined}},{value:{a:Infinity}},{value:new Date()},{kind:'surprise'},{updatedAt:'invalid'}])('fails closed on invalid records %j',patch=>{expect(()=>validateJobuRecords([row('a',patch)])).toThrow();});
 it('does not publish unavailable storage as an empty collection',async()=>{const s=memory();s.readFail=true;const d=controller(s);await d.load();expect(d.get()).toMatchObject({loaded:false,records:undefined,error:'storageRead'});await expect(d.save('a','filter',{name:'x'})).rejects.toThrow();});
 it('publishes only committed writes, retains all revisions and permits safe retries',async()=>{const s=memory(),d=controller(s);await d.load();await d.save('n','doNote',{text:'one'},{operationId:'op1'});s.fail=true;await expect(d.save('n','doNote',{text:'two'},{expectedHead:'op1'})).rejects.toThrow();expect(materializeJobu(d.get().records).get('n').value.text).toBe('one');s.fail=false;await d.save('n','doNote',{text:'two'},{expectedHead:'op1',operationId:'op2'});await d.save('n','doNote',{text:'two'},{expectedHead:'op1',operationId:'op2'});expect(d.get().records).toHaveLength(2);await expect(d.save('n','doNote',{text:'stale'},{expectedHead:'op1'})).rejects.toThrow('conflict');expect(materializeJobu(d.get().records).get('n').value.text).toBe('two');});
 it('remote data held during startup becomes durable before publication and retries failures',async()=>{vi.useFakeTimers();const s=memory(),d=controller(s);await d.applyRemote([row('a')]);expect(d.get().records).toBeUndefined();s.fail=true;await d.load();expect(d.get().records).toEqual([]);s.fail=false;await vi.advanceTimersByTimeAsync(1500);expect(d.get().records).toEqual([row('a')]);expect((await s.read()).value).toEqual([row('a')]);});
 it('two controllers append through real IndexedDB transactions without overwriting',async()=>{const idb=new IDBFactory();const db=await new Promise((res,rej)=>{const req=idb.open('jobu-test',1);req.onupgradeneeded=()=>req.result.createObjectStore('kv');req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error);});disposers.push(()=>db.close());const a=controller(createJoboStore({open:async()=>db}),{uuid:()=> 'a'}),b=controller(createJoboStore({open:async()=>db}),{uuid:()=> 'b'});await Promise.all([a.load(),b.load()]);await Promise.all([a.save('fa','filter',{name:'A'}),b.save('fb','filter',{name:'B'})]);await a.load();expect(a.get().records).toHaveLength(2);});
 it('exports and restores revisions without deleting newer concurrent work',async()=>{const a=controller(memory());await a.load();await a.save('a','filter',{name:'A'});const backup=JSON.parse(a.export());await a.save('b','filter',{name:'B'});await a.restore(backup.records);expect(a.get().records).toHaveLength(2);});
});
describe('Life Planner migration and native lifecycle',()=>{
 it('migrates old document exactly once; old backup is untouched; reopened data matches',async()=>{const doc={...defaultDocument(['Principle']),wishes:[createWish('Write','learning','wish-a')]};const raw=JSON.stringify(doc),storage={getItem:vi.fn(key=>key===STORAGE_KEY?raw:null)};const disk=memory(),d=controller(disk),s=createDurablePlannerStore(d,{storage});await s.load();expect(s.get().wishes[0].title).toBe('Write');const n=d.get().records.length;await s.load();expect(d.get().records.length).toBe(n);await s.commit(current=>updateWish(current,'wish-a',{title:'Revised'},current.wishes[0]));const b=controller(disk),other=createDurablePlannerStore(b,{storage});await other.load();expect(other.get().wishes[0].title).toBe('Revised');expect(raw).toContain('Write');});
 it('does not migrate corrupt legacy data into an empty writable document',async()=>{const d=controller(memory()),s=createDurablePlannerStore(d,{storage:{getItem:()=>'{broken'}});await s.load();expect(s.error()).toBe('format');expect(d.get().records).toEqual([]);await expect(s.commit(x=>x)).rejects.toThrow();});
 it('protects stale wish edits and preserves unrelated entities',async()=>{const disk=memory(),a=controller(disk,{uuid:(()=>{let i=0;return()=>`a${i++}`;})()}),b=controller(disk,{uuid:(()=>{let i=0;return()=>`b${i++}`;})()});const x=createDurablePlannerStore(a,{storage:{getItem:()=>null}}),y=createDurablePlannerStore(b,{storage:{getItem:()=>null}});await x.load();await y.load();await x.commit(d=>({...d,wishes:[createWish('One','learning','one')]}));await b.load();const opened=y.get().wishes[0];await x.commit(d=>updateWish(d,'one',{title:'Changed'},d.wishes[0]));await expect(y.commit(d=>updateWish(d,'one',{title:'stale'},opened))).rejects.toThrow('conflict');await y.commit(d=>({...d,wishes:[...d.wishes,createWish('Two','learning','two')]}));expect(y.get().wishes.map(w=>w.title)).toEqual(['Changed','Two']);});
});
describe('Jobu save → state → file/vault → apply → reload',()=>{
 it('both transports carry immutable rows without task horizon pruning or inferred deletion',async()=>{const a=controller(memory()),b=controller(memory());await a.load();await b.load();await a.restore([row('old',{updatedAt:'2020-01-01T00:00:00Z'}),row('dead',{entityId:'gone',deleted:true})]);const payload={tasks:[],jobuRecords:a.get().records};const merged=mergeSyncData(payload,{tasks:[]});expect(merged.data.jobuRecords).toHaveLength(2);const entityMap=shredState(payload);const remote={};for(const e of entityMap.map(r=>r.entity).filter(e=>e._kind==='jobuRecords')){expect(isInsertOnly(e)).toBe(true);applyRemoteEntity(remote,e);}expect(stable(remote.jobuRecords)).toBe(stable(a.get().records));applyRemoteDelete(remote,'jobuRecords:old');expect(remote.jobuRecords).toHaveLength(2);await b.applyRemote(remote.jobuRecords);await b.load();expect(b.get().records).toEqual(a.get().records);});
});
