import i18n from '../i18n.js';
export const en = {
  title: 'Todoist sync', beta: 'Selective sync · beta',
  intro: 'Todoist supplies tasks; dayGLANCE owns your time blocks. New matching tasks enter the inbox. Native tasks are never exported.',
  token: 'Personal API token', tokenHelp: 'Get it in Todoist → Settings → Integrations → Developer. Keep it private.',
  security: 'The token is kept in this browser session only, not in backups or cloud settings. It is not encrypted against other scripts on this origin. After closing the app, you may need to reconnect.',
  privacy: 'The API reads and caches task/project/label data on this device to evaluate filters. Only matching tasks enter dayGLANCE; those tasks can be included in your normal dayGLANCE backups and cloud sync.',
  connect: 'Connect and load preview', disconnect: 'Disconnect', account: 'Connected: {{name}}',
  enabled: 'Enable selective sync', priorities: 'Priority', projects: 'Projects', labels: 'Labels',
  filters: 'Choose the tasks to sync', all: 'Match every selected group (AND)', any: 'Match any selected group (OR)',
  ruleHelp: 'An empty group is ignored. With all groups empty, nothing syncs. Multiple projects or priorities within a group mean OR.',
  subprojects: 'Include subprojects', labelAll: 'Require all selected labels',
  preview: '{{count}} active tasks match', refresh: 'Refresh preview (read-only)', sync: 'Sync now',
  empty: 'No matching tasks. Check the filters before enabling sync.', noCatalog: 'Connect to load available projects and labels.',
  missing: '{{name}} (not currently available)', interval: 'Automatic sync while the app is open',
  manual: 'Manual only', minutes: 'Every {{count}} minutes',
  writeback: 'Write completed ordinary leaf tasks back to Todoist',
  writeWarning: 'Enable on ONE device only. Existing locally completed linked tasks may be sent. Recurring tasks, parents with active subtasks, and tasks assigned to someone else are not written back. Undo/reopen, task text, dates, labels and projects are NOT sent.',
  safety: 'Removing a filter match or deleting a task never deletes it in the other app. Disconnect pauses sync and keeps tasks and pending operation receipts. Synchronization does not run after the app is closed.',
  recurring: 'Recurring tasks are read-only source records in this beta, not dayGLANCE recurring templates. Complete recurring tasks in Todoist.',
  status: 'Status', idle: 'Idle', syncing: 'Syncing…', success: 'Up to date', error: 'Needs attention',
  last: 'Last successful import: {{date}}', pending: '{{count}} queued completion operations (including paused entries)',
  blocked: '{{count}} completed task(s) cannot be written back safely. Complete these in Todoist:',
  conflicts: 'Both sides changed: choose which value to keep locally. Task text is not written back to Todoist.',
  remote: 'Use Todoist value', local: 'Keep local value', due: 'Todoist due: {{date}}',
  errors: {
    tokenRequired: 'Enter a Todoist API token.', unauthorized: 'Todoist rejected this token. Reconnect with a valid token.',
    networkError: 'The request failed or timed out. Check the network. No third-party proxy is used; this platform must allow direct Todoist API access.',
    cancelled: 'Request cancelled.', invalidResponse: 'Unexpected Todoist response. No missing tasks were treated as deleted.',
    rateLimited: 'Todoist rate limit reached. Automatic requests are paused until the retry window expires.',
    requestFailed: 'Todoist request failed. Local tasks and queued operations were preserved.',
    accountChanged: 'The Todoist account changed. Disconnect and connect again.',
    storageCorrupt: 'The local Todoist sync cache is invalid. Sync is stopped to preserve operation receipts.',
    storageFull: 'Device storage is full or unavailable. Sync stopped before further writes.',
    commandFailed: 'Todoist did not confirm every completion. Unconfirmed operations keep their original request IDs for retry.',
    writeLockUnavailable: 'This environment does not support safe cross-tab write locking. Turn off completion writeback to use read-only sync.',
    busyOtherTab: 'Another dayGLANCE window is syncing Todoist. Try again after it finishes.',
    multiUser: 'Todoist integration is disabled in multi-user mode to avoid sharing personal tasks unintentionally.',
    unknown: 'Sync failed. Local tasks were preserved.',
  },
};
export const zh = {
  title: 'Todoist 同步', beta: '选择性同步 · 测试版',
  intro: 'Todoist 提供任务，dayGLANCE 负责时间安排。符合条件的新任务进入收件箱，不会自动导出 dayGLANCE 本地任务。',
  token: '个人 API Token', tokenHelp: '获取位置：Todoist → 设置 → 集成 → 开发者。请勿把 Token 发到聊天或提交到代码仓库。',
  security: 'Token 仅保存在本次浏览器会话，不进入备份或云同步设置；它不是对同源脚本加密的保险箱。关闭应用后可能需要重新连接。',
  privacy: '为判断筛选范围，API 会读取并在本机缓存任务、项目和标签数据。只有匹配任务导入 dayGLANCE；导入后可随 dayGLANCE 的常规备份、云同步流转。',
  connect: '连接并加载预览', disconnect: '断开连接', account: '已连接：{{name}}',
  enabled: '启用选择性同步', priorities: '优先级', projects: '项目', labels: '标签',
  filters: '选择同步哪些任务', all: '同时满足已选条件组（AND）', any: '满足任意已选条件组（OR）',
  ruleHelp: '未选择的条件组不限制；全部留空则不同步任何任务。同组多个项目或优先级之间为“或”。',
  subprojects: '包括子项目', labelAll: '必须包含全部已选标签',
  preview: '当前匹配 {{count}} 个未完成任务', refresh: '刷新预览（只读）', sync: '立即同步',
  empty: '没有匹配任务，请先检查筛选条件。', noCatalog: '连接后加载可选择的项目和标签。',
  missing: '{{name}}（当前不可用）', interval: '应用打开时自动同步',
  manual: '仅手动', minutes: '每 {{count}} 分钟',
  writeback: '将普通无子任务条目的完成状态回写 Todoist',
  writeWarning: '请仅在一个设备启用。已在本地完成的关联任务也可能被回写。循环任务、含未完成子任务的父任务、分配给他人的任务不回写；撤销完成、标题、日期、标签、项目的本地修改均不回写。',
  safety: '任务不再符合条件或在一端被删除，不会触发另一端删除。断开连接保留本地任务及待确认操作记录。应用关闭后不会继续同步。',
  recurring: '本测试版把循环任务作为只读来源记录，不转换成 dayGLANCE 循环模板。请在 Todoist 中完成循环任务。',
  status: '同步状态', idle: '空闲', syncing: '同步中…', success: '已更新', error: '需要处理',
  last: '上次成功导入：{{date}}', pending: '有 {{count}} 条完成回写操作排队中（含暂停条目）',
  blocked: '以下 {{count}} 个已完成任务不能安全回写，请在 Todoist 处理：',
  conflicts: '两端均有修改，请选择在本地保留哪个版本；任务文字不会回写 Todoist。',
  remote: '采用 Todoist 值', local: '保留本地值', due: 'Todoist 任务日期：{{date}}',
  errors: {
    tokenRequired: '请填写 Todoist API Token。', unauthorized: 'Todoist 拒绝了当前 Token，请重新连接。',
    networkError: '网络请求失败或超时。当前不使用第三方代理；运行平台需要允许直连 Todoist API。',
    cancelled: '请求已取消。', invalidResponse: 'Todoist 返回格式异常，没有将缺失任务视作删除。',
    rateLimited: '触发 Todoist 请求限额，自动请求已暂停至重试时间。',
    requestFailed: 'Todoist 请求失败，本地任务与待确认操作已保留。',
    accountChanged: 'Todoist 账号发生变化，请断开后重新连接。',
    storageCorrupt: '本地同步缓存异常，已停止同步以保护操作记录。',
    storageFull: '本机存储已满或不可写，已停止后续回写。',
    commandFailed: '部分完成操作未获 Todoist 确认，将保留原请求编号以便重试。',
    writeLockUnavailable: '此环境不支持跨窗口写入锁，请关闭完成回写后使用只读同步。',
    busyOtherTab: '另一个 dayGLANCE 窗口正在同步 Todoist，请在其完成后重试。',
    multiUser: '多用户模式下禁用 Todoist 集成，避免意外共享个人任务。',
    unknown: '同步失败，本地任务已保留。',
  },
};
i18n.addResourceBundle('en', 'todoist', en, true, true);
i18n.addResourceBundle('zh-CN', 'todoist', zh, true, true);
